name: Run News Scraper Daily

on:
  schedule:
    - cron: '30 6 * * *'   # 매일 한국 시간 15:30 실행
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Create creds.json from Secret
      run: |
        cat <<EOF > creds.json
        ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        EOF

    - name: Set environment variables
      run: |
        echo "NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}" >> $GITHUB_ENV
        echo "NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }}" >> $GITHUB_ENV
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
        echo "SHEET_ID=${{ secrets.SHEET_ID }}" >> $GITHUB_ENV
        echo "SHEET_NAME=네이버API(첨부파일용)" >> $GITHUB_ENV

    - name: Run Full Main Pipeline
      run: |
        python src/main_pipeline.py

    - name: Upload Collected Data
      uses: actions/upload-artifact@v4
      with:
        name: crawled-news-data
        path: |
          data/
          logs/
